### ISSUE TITLE
PacketRusher: UE/gNB simulator

### ISSUE THREAD

**Issue by linouxis9** [Gradiant/5g-images#222]
Hi Gradiant/Openverso Team,

In case you are looking for a second gNB/UE Simulator or a 5G Core stress tester to evaluate the performance of the 5G Core, you may try my new open-source tool [PacketRusher](https://github.com/HewlettPackard/PacketRusher).
It supports the simulation of multiples UEs and gNodeBs right from a single tool, an high performance N3 tunnel, and it supports some advanced control plane features such as roaming (using open5gs's new roaming feature for example) and gNodeB handover.

If you need any help, feel free to reach out to me :-) I'm looking forward to collaborate!

Cheers,
Valentin

**Comment by cgiraldo** [comment]
Hi Valentin,
the PacketRusher simulator sounds great. We will definitively take a look to it and come back to you. 

Have you try PacketRusher in kubernetes? 
We mainly deploy our 5G services as Cloud-Native network functions in kubernetes (Helm charts). You can take a look to the https://github.com/Gradiant/openverso-charts repository if you are interested.

Cheers,
Carlos

**Comment by linouxis9** [comment]
Hi Carlos!

Thanks for your interest in PacketRusher :-) I know that [some people in the community](https://github.com/Orange-OpenSource/towards5gs-helm/tree/add-packetrusher) are integrating PacketRusher in k8s.
But we have yet ourselves to try PacketRusher in k8s, but it should be able to work provided the gtp5g kernel module is installed on the worker nodes (same requirement as free5gc's UPF) and the pod is running with privileges. We are currently in the process of replacing gtp5g with [eUPF](https://github.com/edgecomllc/eupf)'s eBPF https://github.com/HewlettPackard/PacketRusher/pull/47 which should fix this shortcoming.
I would expect PacketRusher to perform best with Multus's MacVLAN/SR-IOV or host interfaces, but it should work with the default CNI interface.

If I can be of any help for your smooth usage of PacketRusher, feel free to reach out to me! I would be glad to help.

Thanks and cheers,
Valentin

**Comment by avrodriguezgrad** [comment]
Hi @linouxis9 

We've uploaded a PacketRusher image, and a tutorial on how to use it. I've tested it on my laptop, and it works. I'm going to create a Helm chart now, and test PacketRusher in K8s. I'll keep you posted.

BR,
Álvaro

**Comment by linouxis9** [comment]
Excellent @avrodriguezgrad!! Thanks a lot for your hard work! I'll make sure to take a look at your work.

I'll answer on your issue as well :-)

**Comment by linouxis9** [comment]
Also an interesting point to note, is that PacketRusher works with Open5GS's 2.7.0 roaming feature if you are interested in that Open5GS feature! (Just use different MCC/MNC for UE and gNodeB in the configuration).

**Comment by linouxis9** [comment]
Amazing, thanks a lot for your hard work!

Trying PacketRusher with Multus was on my to-do list, so please do share the results on how it goes.

Thanks a lot!

Cheers,
Valentin
