### ISSUE TITLE
Deploying Open5GS UPF container not being able to connect to the internet

### ISSUE THREAD

**Issue by marcohol1** [Gradiant/5g-images#234]
Good day,

I am trying to just deploy an Open5GS UPF container and connect it to my own Open5GS C-plane that is in the host computer. I have my own UE and gNB which connects to the Open5GS core that I have deployed. After starting my Open5GS UPF container, it properly connects to the SMF in my host computer. When I connect the UE to the network, a PDU session is setup but the UE cannot connect to the internet. I see in the UPF container logs that the ogstun device is created but still no internet connection.

Below is my docker compose file:

> 
> version: '3'
> 
> services:
>   upf:
>     image: gradiant/open5gs:2.7.0
>     command:
>     - open5gs-upfd
>     cap_add:
>     - all
>     privileged: true
>     restart: on-failure
>     ports:
>     - 2152:2152
>     sysctls:
>     - net.ipv4.ip_forward=1

I hope you'll be able to help me. Thank you very much for your creation and hope to hear from you soon.

**Comment by avrodriguezgrad** [comment]
Hi @marcohol1 

I have some questions:
- Does your UE reach UPF (ping 10.45.0.1 e.g.) ?
- From UPF container, do you have internet connection?

BR,
Álvaro

**Comment by marcohol1** [comment]
Hi @avrodriguezgrad,

Thank you so much for replying! I noticed that UPF was able to give an IP address to my UE based on the logs in the container. It sees the network based on the PingTools app but it seems like it cannot ping the UPF. Would you have any insights as to why this is happening?

As for your second question, the UPF container does indeed have internet connection. So the main problem right now most probably is between the UE and the UPF. I had made it work when I deployed the UPF in a virtual machine but this is my first time doing it using a container and I am not well-experienced with containers so I am very grateful for your help!

Again, thank you so much!

Best regards,
Marco

**Comment by avrodriguezgrad** [comment]
I dont know about the error of the SMF, sorry for that.

On the other hand, I guess you are using a real gNB and a real UE, I thought all of your environment was virtual. In this case, can you make a ping from gNB to UPF? Have you tried to capture traffic in gNB and UPF and check what the packets are doing? 

I believe this's going to be useful to debug the problem you're having.

**Comment by marcohol1** [comment]
Hi @avrodriguezgrad,

I have been trying out things to make it work. Yes, I am using a real gNB and a real UE. The DU and CU are in 2 different containers in the same network while my Open5GS core is running on the host except the UPF which is running in another container. I made the DU, CU and UPF containers in the same docker network so they are able to ping each other.

When the UE connects, a PDU session is created. Looking at Wireshark, I can see that the UE is sending DNS standard queries but nothing else. I'm wondering if it's a problem with how the docker network is set up or I need to configure something in the iptables or iproute since the UE is already able to make DNS queries but the queries are not being replied to which may mean that it does not go out of the container.

Thanks again!

Best regards,
Marco

**Comment by marcohol1** [comment]
Hi @cgiraldo,

Thanks for your response. Yes, I am running the containers as privileged. The tun interface is created inside the container but the traffic does not go out of the network. I'm thinking of just deploying the whole Open5GS core in separate containers and have them in the same network as the CU and DU containers. I was thinking maybe the problem is the other services are running on the host and maybe it causes some problems but I am not sure.

Thank you again and have a nice weekend!

Best regards,
Marco

**Comment by marcohol1** [comment]
Hi everyone,

I've been analyzing more the problem today and I found out that the UE is able to send DNS requests and even pings to the internet (8.8.8.8). I see from Wireshark the sniffs on the UPF container that it receives the DNS responses and the pings replies. However, it does not go back to the UE. Do you have any insights regarding why this happens?

Thank you very much and have a nice day!

Best regards,
Marco

**Comment by infinitydon** [comment]
Can you confirm:

- if the UPF is able to ping the gNB N3 interface
- if the gNB is able to ping the UPF N3 interface

**Comment by marcohol1** [comment]
Hi @infinitydon,

Thank you for the reply. Yes, both scenarios are possible.

**Comment by infinitydon** [comment]
I will suggest you take a pcap also in the gNB, if you can't see the return GTP packets then it looks like a network/firewall issue between the gNB and UPF N3 interfaces. It can also be an MTU size issue
